name: Build and Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Day1 Smoke-test
        working-directory: day1
        run: ./gradlew build
      - name: Day2 Smoke-test
        working-directory: day2
        run: ./gradlew build
      - name: Day3 Smoke-test
        working-directory: day3
        run: ./gradlew build
      - name: Day4 Smoke-test
        working-directory: day4
        run: ./gradlew build
      - name: Day4 Smoke-test
        working-directory: day4
        run: ./gradlew build
      - name: Day5 Smoke-test
        working-directory: day5
        run: ./gradlew build
      - name: Day6 Smoke-test
        working-directory: day6
        run: ./gradlew build